#!/usr/bin/env php
<?php

use Fajar\Bandung\Kernel\CommandKernel;
use Fajar\Bandung\Kernel\Kernel;

require_once __DIR__ . '/vendor/autoload.php';

/**
 * console command flow
 * first we load environment variable
 * then we register kernel to binding all console command dependency from app directory
 * then we create command kernel to run console command
 */

$appDir = __DIR__ . '/app';
$container = (new Kernel)
    ->loadEnv(__DIR__)
    ->registerCommandDependency($appDir);

//$_SERVER['argv']
$app = new CommandKernel($container, new \Symfony\Component\Console\Input\ArgvInput);
$app->run();

exit;